language: python


python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

#addons:
    #apt:
        #packages:
#            - graphviz
#            - texlive-latex-extra
#            - dvipng

env:
    global:
        - secure: LM5pr9xbwuf2v/lxUGr8WuHUTVSdaxmTQ1w+0HRcwbGykVISv0BzEUnfjxpTv8n4Cg3Ni2cHUhMsv8yZlXofTH7uCxkJkA6yJpG/7IHhJAKnYYIvaZAVyTEk6CCTc5b+rBgA7Akpcwpn44FIoZ75jEetkcyBsbtDSC/kDGVjWfrUdavkEfuOgGg4GvEllIfq5QDs0HvgE86CLngerH5NgLcfusXVyd/oVDdKiANXLATzEedJRA2IneyDe0t4TwRtlTdDAqFAyExqQuAfbhFWJlOehcR6R0l2fR+/imR2BZrcXQQsHjgyXe0M+4zVa06SZ89aRZBbEC+zQtTFdESLHSFPtGOhz2B9fnb4wQXEqg8qixbFXb3hjrgIdlptYeCZKNmD8F0h2+MYAle54uolivdcIxlSpkUYy9/Iru/vf+0fCddDXVJd2aHvIRJ4yWjJbqPNkaz6MISL+uZHU8doUgyGEn5oMv/Q+Rc0KPwPNIxB8i1UYfsgOHR2t3Un66sTquujiq5GSO9PrvuuxorOTeF/qxba9tQPm/+FeLB0vIrvdKID8kWlBdXolMywtD6yk1PI2Q/w5g8tdFVd50bvC+t8bkHvwHe6HgYAnlODB0qkX0Bd+YBtq/zhh1VCkPD0NUEhSGIzCqEhZX14ShEClF1hV0GEghRHqJ3GFOtcIhE=

    matrix:
        - SETUP_CMD='test'

matrix:
    include:

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        #- python: 2.7
        #  env: SETUP_CMD='build_sphinx -w'

    exclude:

        #- python: 3.3
        #  env: SETUP_CMD='test'
          
install:
    - pip install -U pip
    - pip install twine
    - for i in $(ls -d */); do cd $i; pip install -r dev_requirements.txt; cd ..; done
    - pip install coveralls

script:
    - for i in $(ls -d */); do cd $i; pytest --cov $i || exit 1; cd ..; done

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then echo "HERE"; coverage combine $(ls -d */.coverage) || exit 1; coveralls; fi

jobs:
  include:
    - stage: deploy
      python: 3.4
      deploy:
         provider: script
         script: ./.deploy.sh
         on:
            tags: true
            repo: opencadc/caom2tools
            branch: master
