language: python


python:
    #- 2.7
    #- 3.3
    - 3.4
      #- 3.5
      #- 3.6

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

#addons:
    #apt:
        #packages:
#            - graphviz
#            - texlive-latex-extra
#            - dvipng

env:
    global:
        - secure: MHpBo9IJ/7LOfLKfaHeenHNlMSTp35PogYPb9Z+PqY+BqWw7uVF0KKtJOMio/I/oSsMM9BfoFU6sX7ihE05/vtcL+4DP8pi52UyFCjvSva+5BfxoxOUWYcZmsfbUTu8P5Cat+XSlVroAlbagocObl1NF9nL3NXjk3MxBq4StEl7yMBhwkGt3Nfpl++X8t2CgzhtTYA6x86eXzml5V+IYnXeO7LtglG8o1oJQ0edf+LZtTr7C8C95aeWZYgJP9uZN8aVTB62MoFb3AqNT/+S3HNNk1Az6LnUkWb3znTVTHzf6f8Dh3CCW3qqPy2kGJqNo9o55bI6WKJ+i35dUGSl9kWJ8myH+sU9pkjGDmowkgsEQIeM+A1BNRArEWnlIpCC+2q37DKH+ny2+Pqh5BOz40Yr0HYKJKK9ecJ+JvyjNJPBg8CfHORLC10kb42VO7F8wxEChqjuv/u1Cjj9LjZsL3bFNulG01gNOE7UUeVVyWz7SjK2mNkHLElMlddQgQGacBLqs5PX09SyqwxnsIq1TGFqWtdTeDxkVfQpf6tNbyTRfjdq2pywck3eTx1LRrzgerKh1dCd8ZqUTwo0PNHA/jLQQSRfcxPHSgZYp1tGKPxI8k3dxV0huK+mTTecACz5g5Rqe4B0GGuXU5uL3qybl7EfxhTonlDhsJjQKmlMcikM=

        - SETUP_CMD='test'

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='test'

matrix:
    include:

        # Do a coverage test in Python 2.
        #- python: 3.4
        #  env: SETUP_CMD='coverage'

        # Do a egg-info test in Python 2.
        - python: 3.4
          env: SETUP_CMD='deploy'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        #- python: 2.7
        #  env: SETUP_CMD='build_sphinx -w'

    exclude:

        #- python: 3.3
        #  env: SETUP_CMD='test'
          
install:
    - pip install -U pip
    - pip install twine
    #- for i in $(ls -d */); do cd $i; pip install -r dev_requirements.txt; cd ..; done
    #- pip install coveralls

script:
    - ls
    #- for i in $(ls -d */); do cd $i; pytest --cov $i || exit 1; cd ..; done

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $SETUP_CMD == 'coverage' ]]; then coverage combine $(ls -d */.coverage) || exit 1; coveralls; fi


deploy:
  provider: script
  script: deploy.sh
  on:
    tags: true
    repo: andamian/caom2tools
    branch: hotfix
    condition: "$SETUP_CMD = 'deploy'"

