language: python


python:
    #- 2.7
    #- 3.3
    - 3.4
      #- 3.5
      #- 3.6

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

#addons:
    #apt:
        #packages:
#            - graphviz
#            - texlive-latex-extra
#            - dvipng

env:
    global:

        - SETUP_CMD='test'

    matrix:
        # Make sure that egg_info works without dependencies
        - SETUP_CMD='test'

matrix:
    include:

        # Do a coverage test in Python 2.
        #- python: 3.4
        #  env: SETUP_CMD='coverage'

        # Do a egg-info test in Python 2.
        - python: 3.4
          env: SETUP_CMD='deploy'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        #- python: 2.7
        #  env: SETUP_CMD='build_sphinx -w'

    exclude:

        #- python: 3.3
        #  env: SETUP_CMD='test'
          
install:
    - pip install -U pip
    - for i in $(ls -d */); do cd $i; pip install -r dev_requirements.txt; cd ..; done
    - pip install coveralls

script:
    - for i in $(ls -d */); do cd $i; pytest --cov $i || exit 1; cd ..; done

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $SETUP_CMD == 'coverage' ]]; then coverage combine $(ls -d */.coverage) || exit 1; coveralls; fi

before_deploy:
    # do an egg test
    - echo "Installing " $(echo $TRAVIS_TAG | awk -F '-' '{print $1}');
                        cd $(echo $TRAVIS_TAG | awk -F '-' '{print $1}');
                        grep "version = $(echo $TRAVIS_TAG | awk -F '-' '{print $2}')" setup.cfg || echo "Mismatch between the tag version and package version" && exit -1;
                        python setup.py egg_info
    
deploy:
  provider: pypi
  user: Canadian.Astronomy.Data.Centre
  password:
    secure: QG7tc9q7IbWO5nH/fFUSuX61mcqp6vIN2GNbMi177+q3BVhamIe8uWXvLFMsmgnCSj8+lA1EUNNiVlODnAao9EMC2iBgs8NRkj46BtEKuB4Rw6MV7ZLFPmR+zuir3JmBjv81eOC+OizZIxz+n7pjusHgNxlLrXt+RfdkVQIwOLq82GfrfMQcMYArgo6ekovsO+GcySqlm0r6omE6d/rKNYgZGHsw9shNsNncLc34igZTRByRj+zNtrmlxxiLMmk4aAA0xCPFgmQxdzl3HSZnfSXPDZM9L5qtEaW8Sfm2PetEWzk8rR1YQYIVNy0T+PjLPtk4++3xMaTttD6fVWYrmN4tlhBlWZRuUS/1NU/NzYJ+jtQ7PUPzedJ8HidHFeI/OqehHaK9J9O1QoPiPgzEzz5BCtwc3M9SneJwcaHJdIp+VMNgq5o/zSQbTlAKgbGaqNabi+GG4QKjvjsD7MegY5dm/T2ZibfACz4hGoSrsmKtYTGwYz0WBdD4okdoZo7a/uKG8gc4vCRoDcg1jh1J7jBDb2tMrQc9Noa8YkRGBlC2BEMGN+EaRtfk9GzkDaFWxKfswQHwQ0313NB4oDmLBdxUawmg/R+YrQnpGMl45Vc9bBDOVBnLTNO6AftFNnPT2Cc8fUlG8V3Xhc2PJLgSUC5436c/E0dpyg8wbbEcxEc= 
  on:
    tags: true
    repo: andamian/caom2tools
    branch: hotfix
    condition: "$SETUP_CMD = 'deploy'"

after_deploy:
    - ls dist
